### ISSUE TITLE
arch: Cleanup

### ISSUE THREAD

**Issue by ckoehn** [ckoehn/dotfiles#46]
https://github.com/ckoehn/dotfiles/blob/3c8a3137a585fd39900aafc053aad00b416ca139/arch/setup.sh#L174

**Comment by dermorz** [comment]
I would not copy it to /mnt in the first place. You only need to do that because you in stall the packages from `setup-chroot.sh` which you call by `chroot ./setup-chroot.sh ...` and you cannot access the "outside" anymore.

I opted for installing the packages directly from the `setup.py` cleaning the `packages.txt` outside of the chroot and pipe that into `chroot pacman -S --needed --noconfirm -`.

But maybe you want that file structure with split bash scripts…
